Dockerfiles for backends and frontends and docker compose
LissaGreense/water-movie-melon pull request #8
Opened 2024-06-06 20:58 UTC by kajedot

2024-06-06 21:18 UTC, LissaGreense requested changes

2024-06-06 21:18 UTC, LissaGreense commented on frontend/Dockerfile
> +CMD ["npm", "run", "dev"]
We can't run dev server in docker file

2024-06-06 21:18 UTC, LissaGreense commented on frontend/package.json
> +    "dev": "vite --host",
remove it

2024-06-18 20:46 UTC, kajedot commented on frontend/Dockerfile
> +CMD ["npm", "run", "dev"]
fixed: CMD ["npm", "run", "preview"]

2024-06-18 20:48 UTC, kajedot commented on frontend/package.json
> +    "dev": "vite --host",
I would leave it for testing

2024-06-18 21:24 UTC, kajedot commented on frontend/package.json
> +    "dev": "vite --host",
deleted

2024-06-18 21:36 UTC, LissaGreense approved these changes
nice

2024-06-18 21:40 UTC, merged